name: ll-stochastic-depth
channels:
  - pytorch
  - default
dependencies:
  - cudatoolkit=11.3.1
  - pytorch=1.10.0
  - torchvision
  - autopep8
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - seaborn
  - pylint
  - rope
  - mlflow
  - pip
  - pip:
    - git+https://github.com/ContinualAI/avalanche.git