name: stochastic-depth
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.8.5
    - pytorch=1.5.1
    - torchvision=0.6.1
    - cudatoolkit=10.2
    - numpy
    - scikit-learn
    - tqdm
    - pylint
    - autopep8
    - rope
    - pytorch-lightning
    - matplotlib
    - pandas
    - imbalanced-learn